name: md2pdf

on:
  push:
    branches:    
      - main

jobs:
  md2pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir pdf_output
      - uses: docker://pandoc/latex
        with:
          args: --pdf-engine=xelatex nlp.md -o pdf_output/test.pdf
      - uses: actions/upload-artifact@master
        with:
          name: build
          path: pdf_output
